### ISSUE TITLE
Songbook action not working

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/fappen#75] opened 2024-05-17 07:55 UTC
I can't get the songbook build script working. I trigger it, but it never generates a PR

**Comment by jonasKjellerup** [comment] 2024-05-22 17:39
The CI script technically works as intended. It doesn't generate a PR because there are no new changes changes to create a PR for.

It is an artifact of a time where we had the generated `songs.json` included in the git tree.
It has since been excluded. 

So currently, the job is kinda pointless, and broken in subtly hilarious ways:
```
Run python util/build_songs.py

Downloading songbook 0%
Downloading songbook -819200%
Downloading songbook -1638400%
Downloading songbook -2457600%
Downloading songbook -3276800%
Downloading songbook -4096000%
```

I think this a wontfix case, since build artifact should be avoided in the git tree.
If you disagree feel free to reopen 😄

**Closed by jonasKjellerup** 2024-05-22 17:39 UTC
Labels: c-bug, wontfix, c-workflow
